jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${{ secrets.JENKINS_ADMIN_ID }}
          password: ${{ secrets.JENKINS_ADMIN_PASSWORD }}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - Overall/Administer:${{ secrets.JENKINS_ADMIN_ID }}
        - Overall/Read:authenticated
  remotingSecurity:
    enabled: true
security:
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "github-credentials"
              secret: ${{{ secrets.GIT_HUB_PRIVATE_KEY }}}
unclassified:
  location:
    url: http://${SERVER_IP}:8080/
  ghprbTrigger:
    auths:
    - githubAuth:
        credentialsId: "github-credentials"
        description: "Anonymous connection"
        id: "github-credentials"
        secret: ${{{ secrets.GIT_HUB_PRIVATE_KEY }}}
        serverAPIUrl: "https://api.github.com"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    configs:
    - credentialsId: "github-credentials"
      manageHooks: false
      name: "GitHub"
    hookUrl: "http://${SERVER_IP}:8080/github-webhook/"
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
jobs:
  - githubPullRequest:
      plugin: github
      spec: |
        pipelineJob('aurora-labs-ex-merge-requests') {
          definition {
            cpsScm {
              scm {
                git {
                  remote {
                    url('https://github.com/yarinago/*.git')
                    credentials('github-credentials')
                  }
                  branches('*')
                  extensions {
                    gitSCMExtension {
                      relativeTargetDir('Aurora-Labs-Ex')
                    }
                  }
                }
              }
              scriptPath('Jenkinsfile')
            }
          }
        }